title: РО Прайм Нотес
remote_theme: pmarsceill/just-the-docs
# color_scheme: "dark"
search_enabled: false
url: "https://roprime.lpk.one"
footer_content: "Copyright &copy; 2021 Zizyazium. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
plugins:
  - jekyll-remote-theme
aux_links:
  "GitHub":
    - "https://github.com/lpkone/roprime-notes"
ga_tracking: UA-53520445-2
